/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.practice.talbot3;

import io.reactivex.rxjava3.core.*;
import io.reactivex.rxjava3.schedulers.Schedulers;

public class App {
   public String getGreeting() {
      return "hello world";
   }
   public static void main(String args[]){
      Flowable.range(1, 10)
      .flatMap(v ->
          Flowable.just(v)
            .subscribeOn(Schedulers.computation())
            .map(w -> w * w)
      )
      .blockingSubscribe(System.out::println);   
   }
}
